Warm Up- Numpy and Functions
Create a new .py file called number_finder.

In the number_finder.py file create 2 functions. The first function (called prime_finder) will select only the prime #'s from a given numpy array. The second function (called fibonacci_finder) will select only the Fibonacci numbers from a given numpy array.

Now open a new jupyter notebook.

In your jupyter notebook import number_finder.

Next create an array called numbers that contains 100 random numbers.

Apply both number_finder functions to the array you created to find the prime and fibonacci numbers contained in your array.

BONUS

Create an additional function to find the tribonacci numbers in your array.

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import number_finder as nf

In [3]:
a = np.array([1,2,3,4,5,6,7, 9])
a

array([1, 2, 3, 4, 5, 6, 7, 9])

In [4]:
nf.prime_finder(a)

array([2, 3, 5, 7])

In [5]:
nf.prime_finder(a)

array([2, 3, 5, 7])

In [6]:
fib = [0,1,1,2,3,4,4,8,1,9]

In [19]:
tri = [0,1,1,2, 4,5,11]
nf.tribonacci_finder(tri)

array([ 2,  4, 11])

In [8]:
nf.fibonacci_finder(fib)

array([1, 2, 3, 8, 9])

In [13]:
rand_array = np.random.randint(low=1, high=100, size=1000)

In [14]:
nf.prime_finder(rand_array)

array([ 5, 41, 79,  7, 31, 29, 53, 47, 89, 23, 43,  5, 17, 97, 13, 73, 73,
       11, 61, 97, 73, 59, 19, 13,  3, 71, 53,  5, 53, 23, 17, 29, 79, 31,
        3, 89, 43, 37,  3, 43, 47, 67, 13, 97,  7, 47, 43, 79, 71, 79, 67,
        5, 83,  7, 41, 13, 13, 53, 37, 61, 43, 71, 37, 97, 37, 71, 23, 97,
       41, 53,  5, 29, 43, 53, 83, 47, 53, 11, 53, 41, 47, 67,  5, 83, 17,
       43, 29, 41, 37, 43,  7, 23, 59,  2, 19, 23, 61, 97, 83, 79, 47, 29,
       79, 17, 89, 31, 61,  2, 31, 19, 31, 89, 97, 19, 13, 19, 89, 79, 71,
       59, 13,  7, 71, 59, 31, 19, 41,  3, 11,  5, 41, 17, 59, 19, 89, 23,
       53, 13, 13, 73, 61, 23, 17, 61, 59, 17, 53, 11, 89, 73, 43, 61,  5,
       41, 31,  3, 97, 73, 97, 79, 19, 31, 47, 17, 67, 17, 89, 37, 41,  3,
       29, 47, 53, 59, 97,  2, 83, 13, 89, 23, 13, 61, 59,  5, 29, 59, 59,
       97, 61, 43,  3, 11,  7, 43, 71,  2, 47,  5, 23, 47, 11, 17, 17, 61,
       13,  5, 11, 71, 31,  7, 71,  7, 73, 43,  7, 19, 31, 11, 53, 79, 31,
       41,  5, 73, 13, 53

In [15]:
nf.fibonacci_finder(rand_array)

array([ 9, 84, 66])

In [20]:
tri_rand_array = np.random.randint(low=1, high=100, size=1000)

In [21]:
nf.tribonacci_finder(tri_rand_array)

array([78, 85])